"""Update item table

Revision ID: 26619122d81d
Revises: 20ba2360bdb1
Create Date: 2022-06-20 14:27:51.870337

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26619122d81d"
down_revision = "20ba2360bdb1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("amount", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "amount")
    # ### end Alembic commands ###
