version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8009:80
    environment:
      - DATABASE_URL=postgresql://ecommerce:123@db:5432/ecommerce_db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=ecommerce
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ecommerce_db

volumes:
  postgres_data_prod: