version: '3.3'

services:
  web:
    build: .
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;
      alembic upgrade head;
      uvicorn app.main:app --host 0.0.0.0 --reload'
    volumes:
      - .:/app
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://ecommerce:123@db:5432/ecommerce_db
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=ecommerce
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ecommerce_db
  traefik:
    image: traefik:v2.2
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data: